version: 0.0
os: linux

files:
  - source: /
    # destination: /home/ec2-user/build/
    destination: /home/dp_user/build/
permissions:
  - object: /home/dp_user/
    pattern: "**"
    # owner: root
    # group: root
    owner: dp_user
    group: dp_user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/deploy_before.sh
      timeout: 60
      # runas: root
      runas: dp_user
  ApplicationStart:
    - location: scripts/web_start.sh
      timeout: 60
      # runas: root
      runas: dp_user