version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/build/
permissions:
  - object: /home/ec2-user/build/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStart:
    - location: /home/ec2-user/build/app_start.sh
      timeout: 300
      runas: ec2-user
  # ApplicationStart_web:
  #   - location: /home/ec2-user/build/web_start.sh
  #     timeout: 300
  #     runas: ec2-user