version: 0.0
os: linux

files:
  - source:  /
    destination: /home/tomcat/apache-tomcat-10.1.12/webapps/
permissions:
  - object: /home/tomcat/apache-tomcat-10.1.12/webapps/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777

hooks:
  AfterInstall:
    - location: start.sh
      timeout: 300
      runas: ec2-user