version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/build/
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:
  # BeforeInstall:
  #   - location: scripts/set_app_env.sh
  #     timeout: 300
  #     runas: ec2-user
  #   - location: scripts/app_init.sh
  #     timeout: 300
  #     runas: ec2-user
  AfterInstall:
    - location: app_start.sh
      timeout: 300
      runas: root