version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/build/
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/deploy_before.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/web_start.sh
      timeout: 60
      runas: root