version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/build/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/set_web_conf.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: web_start.sh
      timeout: 300
      runas: ec2-user