version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build Started
      - sudo chmod +x gradlew
      - ./mvnw clean install -DskipTests
  post_build:
    commands:
      - echo $(basename ./target/*.war)
      - pwd
artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/**
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
