version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo Build Started on `date`
      - sudo chmod +x mvnw
      - ./mvnw clean package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd

artifacts:
  files:
    - target/spring-petclinic.war
    - app/appspec.yml
    - scripts/app_start.sh
    - scripts/deploy_before.sh
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'