version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/build/
permissions:
  - object: /home/ec2-user/build/
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:
  ApplicationStart:
    - location: app_start.sh
      timeout: 300
      runas: root